version: '3'

services:
    calc-api:
        container_name: calc-api
        image: node:12
        restart: unless-stopped
        volumes:
            - .:/app
        working_dir: /app
        command: bash -c "yarn install && make dev && ls -full"
        ports:
            - "3001:3001"
            - "3002:3002"